### ISSUE TITLE
Will it work with Python under windows?

### ISSUE THREAD

**Issue by SJPadbury** [l3uddz/plex_dupefinder#16]
When attempting to run, after pip installing the items listed in requirements, I get the following:

C:\Python27\Scripts\plex_dupefinder>.\plexdupes.py
Traceback (most recent call last):
  File "C:\Python27\Scripts\plex_dupefinder\plexdupes.py", line 11, in <module>
    from config import cfg
  File "C:\Python27\Scripts\plex_dupefinder\config.py", line 146, in <module>
    tmp = load_config()
  File "C:\Python27\Scripts\plex_dupefinder\config.py", line 99, in load_config
    return AttrConfig(json.load(fp))
  File "C:\Python27\Scripts\plex_dupefinder\config.py", line 33, in __init__
    super().__init__(config)
TypeError: super() takes at least 1 argument (0 given)

C:\Python27\Scripts\plex_dupefinder>

Is this a Windows not supported issue, or did I screw something up along the way?

**Comment by Anaerin** [comment]
You need Python 3 or higher. It won't work with Python 2.7
