### ISSUE TITLE
something wrong on my Mac OS 

### ISSUE THREAD

**Issue by martinorob** [l3uddz/plex_dupefinder#20]
Hi,

when I run plex_dupefinder I have this errors:

`python plexdupes.py
Traceback (most recent call last):
  File "plexdupes.py", line 11, in <module>
    from config import cfg
  File "/Users/martinoroberto/Scripts/plex_dupefinder/config.py", line 146, in <module>
    tmp = load_config()
  File "/Users/martinoroberto/Scripts/plex_dupefinder/config.py", line 99, in load_config
    return AttrConfig(json.load(fp))
  File "/Users/martinoroberto/Scripts/plex_dupefinder/config.py", line 33, in __init__
    super().__init__(config)
TypeError: super() takes at least 1 argument (0 given)`

this is my config file

cat config.json

`{
  "AUDIO_CODEC_SCORES": {
    "Unknown": 0,
    "aac": 1000,
    "ac3": 1000,
    "dca": 2000,
    "dca-ma": 4000,
    "eac3": 1250,
    "flac": 2500,
    "mp2": 500,
    "mp3": 1000,
    "pcm": 2500,
    "truehd": 4500,
    "wmapro": 200
  },
  "AUTO_DELETE": false,
  "FILENAME_SCORES": {
    "*.avi": -1000,
    "*.ts": -1000,
    "*.vob": -5000,
    "*1080p*BluRay*": 15000,
    "*720p*BluRay*": 10000,
    "*HDTV*": -1000,
    "*PROPER*": 1500,
    "*REPACK*": 1500,
    "*Remux*": 20000,
    "*WEB*CasStudio*": 5000,
    "*WEB*KINGS*": 5000,
    "*WEB*NTB*": 5000,
    "*WEB*QOQ*": 5000,
    "*WEB*SiGMA*": 5000,
    "*WEB*TBS*": -1000,
    "*WEB*TROLLHD*": 2500,
    "*WEB*VISUM*": 5000,
    "*dvd*": -1000
  },
  "FILEPATH_SCORES": {},
  "PLEX_SECTIONS": {
    "Film": 0
  },
  "PLEX_SERVER": "https://plex.myDomain.com",
  "PLEX_TOKEN": "myToken",
  "SCORE_FILESIZE": true,
  "SKIP_LIST": [],
  "VIDEO_CODEC_SCORES": {
    "Unknown": 0,
    "h264": 10000,
    "h265": 5000,
    "hevc": 5000,
    "mpeg1video": 250,
    "mpeg2video": 250,
    "mpeg4": 500,
    "msmpeg4": 100,
    "msmpeg4v2": 100,
    "msmpeg4v3": 100,
    "vc1": 3000,
    "vp9": 1000,
    "wmv2": 250,
    "wmv3": 250
  },
  "VIDEO_RESOLUTION_SCORES": {
    "1080": 10000,
    "480": 3000,
    "4k": 20000,
    "720": 5000,
    "Unknown": 0,
    "sd": 1000
  }
}`

May you help me!

**Comment by martinorob** [comment]
#solved.

Python3 is required.
