### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections'

### ISSUE THREAD

**Issue by jobrien2001** [l3uddz/plex_dupefinder#62]
**Logs**
```Traceback (most recent call last):
  File "/tools/plex_dupefinder/plex_dupefinder.py", line 11, in <module>
    from config import cfg
  File "/tools/plex_dupefinder/config.py", line 8, in <module>
    from attrdict import AttrDict
  File "/usr/local/lib/python3.10/dist-packages/attrdict/__init__.py", line 5, in <module>
    from attrdict.mapping import AttrMap
  File "/usr/local/lib/python3.10/dist-packages/attrdict/mapping.py", line 4, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```
**Additional context**
I recently started getting this error.  Any ideas why? maybe a plex update?

**Comment by saltydk** [comment]
Doesn't support Python 3.10
